config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]

  root 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses, :dependent => :destroy
  has_many :ingredients, through: :doses


end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :ingredient, :uniqueness => {:scope => :cocktail}
  belongs_to :cocktail
  belongs_to :ingredient

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses # through:
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]
  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def edit
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
     @cocktail = @cocktail
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def update
    if cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail)
    else
      render :edit
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktail_url
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
      params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, except: [:destroy]
  def new
    @ingredients = Ingredient.all - @cocktail.ingredients
    @dose = Dose.new
  end

  def create
    # raise
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @ingredients = Ingredient.all - @cocktail.ingredients
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_cocktail
  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.cocktail = @cocktail
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= form_with(model: cocktail, local: true) do |form| %>
  <% if cocktail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cocktail.errors.count, "error") %> prohibited this cocktail from being saved:</h2>

      <ul>
      <% cocktail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cocktail_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Editing Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<h1>cocktail</h1>
<ul>
  <% @cocktails.each do |cocktail| %>
  <li>
    <h3>
      <%= link_to cocktail.name, cocktail_path(cocktail) %>
    </h3>
  </li>
  <% end %>
</ul>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cocktail.name %>
</p>

<h3> Ingredients </h3>

<ul>
<% @cocktail.doses.each do |dose| %>
  <li>
    <p>
      <%= dose.description %>
    </p>
    <p>
      <%= dose.ingredient.name  %>
    </p>
  <%= link_to 'Delete', dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %>
  </li>
<% end %>
</ul>




<%= link_to 'Add dose', new_cocktail_dose_path(@cocktail) %>
<%= link_to 'Edit', edit_cocktail_path(@cocktail) %> |
<%= link_to 'Back', cocktails_path %>

app/views/doses/new.html.erb
<h1 class="text-center">
  update a cocktail!
</h1>
<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.input :ingredient_id, collection: @ingredients %>
  </div>
  <div class="form-submit">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>